# Generated by Django 3.2.6 on 2021-08-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField()),
                ('dob', models.IntegerField()),
                ('district', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('adhaarno', models.BigIntegerField()),
            ],
        ),
    ]
