# Generated by Django 3.2.6 on 2021-08-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maincourse', models.CharField(max_length=50)),
                ('Starter', models.CharField(max_length=50)),
                ('Dessert', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
